package es.jesus.ampodcasts;

import android.app.*;
import android.graphics.Color;
import android.os.Bundle;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

public final class RecommendationsActivity extends Activity {
    private final ExecutorService worker=Executors.newSingleThreadExecutor();private Future<?> task;
    private LinearLayout root,results;private TextView status;private Button find;
    @Override public void onCreate(Bundle state){super.onCreate(state);UiPreferences.apply(this);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.BLACK);root.setPadding(dp(20),dp(16),dp(20),dp(16));root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(20)+i.getSystemWindowInsetLeft(),dp(16)+i.getSystemWindowInsetTop(),dp(20)+i.getSystemWindowInsetRight(),dp(16)+i.getSystemWindowInsetBottom());return i;});setContentView(root);render();}
    private void render(){root.removeAllViews();button(root,"Volver",this::finish);text(root,"Para ti",26,0xffa8c7fa);text(root,"Descubre programas a partir de los temas de tus escuchas. Las sugerencias proceden del catálogo público y pueden no coincidir con tus gustos.",14,0xffa6abb3);
        Switch enabled=new Switch(this);enabled.setText("Recomendaciones personales");enabled.setTextColor(Color.WHITE);enabled.setMinHeight(dp(48));enabled.setChecked(Recommendations.enabled(this));UiStyle.toggle(enabled);root.addView(enabled,UiStyle.spaced(this));enabled.setOnCheckedChangeListener((b,value)->{if(!value){Recommendations.enabled(this,false);cancel();render();return;}enabled.setChecked(false);new AlertDialog.Builder(this).setTitle("Activar Para ti").setMessage("Onda guardará en este móvil los temas detectados por Gemini de los episodios que escuches al menos 30 segundos, hasta 100 episodios. Tus favoritos tendrán más peso.\n\nAl pulsar Buscar recomendaciones se enviarán hasta tres temas al catálogo público de Apple Podcasts. No se enviarán el audio, la clave API ni tu historial completo. No se hacen solicitudes adicionales a Gemini.\n\nPuedes desactivar esta función o borrar su historial. El historial no forma parte de la copia de seguridad.").setNegativeButton("Cancelar",null).setPositiveButton("Activar",(d,w)->{Recommendations.enabled(this,true);render();}).show();});
        button(root,"Borrar historial de Para ti",()->new AlertDialog.Builder(this).setTitle("Borrar historial de Para ti").setMessage("Se borrarán los temas usados para recomendar. Tus favoritos, progreso y capítulos se conservarán. Si mantienes la función activa, aprenderá de las próximas escuchas.").setNegativeButton("Conservar",null).setPositiveButton("Borrar",(d,w)->{Recommendations.clear(this);cancel();render();}).show());
        status=text(root,"",14,0xffa6abb3);find=button(root,"Buscar recomendaciones",this::search);find.setEnabled(Recommendations.enabled(this));ScrollView scroll=new ScrollView(this);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);scroll.addView(results);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        if(!Recommendations.enabled(this)){status.setText("Activa Para ti para aprender de tus próximas escuchas.");return;}List<Recommendations.Interest> interests=Recommendations.interests(this);StringBuilder labels=new StringBuilder();for(Recommendations.Interest i:interests){if(labels.length()>0)labels.append(" · ");labels.append(i.topic);}status.setText(interests.isEmpty()?"Escucha al menos 30 segundos de un episodio con temas de Gemini para empezar. Los análisis de betas anteriores se pueden actualizar desde Gemini Beta.":"Tus temas: "+labels+". Busca para consultar el catálogo.");
    }
    private void search(){List<Recommendations.Interest> interests=Recommendations.interests(this);if(interests.isEmpty()){status.setText("Todavía no hay temas de escuchas suficientes.");return;}long revision=Recommendations.revision(this);find.setEnabled(false);results.removeAllViews();status.setText("Buscando programas sobre tus temas…");Set<String> followed=new HashSet<>();for(Podcast p:new Repository(this).podcasts())followed.add(p.feed);
        task=worker.submit(()->{try{List<Recommendations.Suggestion> suggestions=Recommendations.search(interests,followed,topic->{if(!Recommendations.enabled(this) || Recommendations.revision(this)!=revision)throw new InterruptedException();return Catalog.search(topic);});runOnUiThread(()->{if(isDestroyed() || !Recommendations.enabled(this) || Recommendations.revision(this)!=revision)return;find.setEnabled(true);status.setText(suggestions.isEmpty()?"No se encontraron programas nuevos para estos temas. Prueba después de otras escuchas.":"Sugerencias por afinidad de temas · elige cuáles añadir");Set<String> current=new HashSet<>();for(Podcast p:new Repository(this).podcasts())current.add(p.feed);for(Recommendations.Suggestion suggestion:suggestions)if(!current.contains(suggestion.podcast.feed))show(suggestion);});}catch(Exception e){runOnUiThread(()->{if(isDestroyed() || !Recommendations.enabled(this) || Recommendations.revision(this)!=revision)return;find.setEnabled(true);status.setText("No se pudo consultar el catálogo. Comprueba la conexión y reintenta.");});}});
    }
    private void show(Recommendations.Suggestion suggestion){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(12),dp(14),dp(12));android.graphics.drawable.GradientDrawable background=new android.graphics.drawable.GradientDrawable();background.setColor(0xff14181f);background.setCornerRadius(dp(20));card.setBackground(background);LinearLayout.LayoutParams layout=new LinearLayout.LayoutParams(-1,-2);layout.setMargins(0,dp(10),0,dp(4));results.addView(card,layout);text(card,suggestion.podcast.title,19,Color.WHITE);text(card,"Porque escuchas «"+suggestion.reason.topic+"» en "+suggestion.reason.program,14,0xffa6abb3);Button add=button(card,"Añadir a biblioteca",()->{try{boolean added=new Repository(this).addPodcast(suggestion.podcast);Toast.makeText(this,added?"Añadido a tu biblioteca":"Ya está en tu biblioteca",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"No se pudo añadir el programa",Toast.LENGTH_LONG).show();}});add.setContentDescription("Añadir "+suggestion.podcast.title+" a la biblioteca");}
    private void cancel(){if(task!=null)task.cancel(true);task=null;}
    private TextView text(LinearLayout parent,String value,int size,int color){TextView view=new TextView(this);view.setText(value);view.setTextSize(size);view.setTextColor(color);view.setPadding(0,dp(8),0,dp(8));parent.addView(view);return view;}
    private Button button(LinearLayout parent,String label,Runnable action){Button button=new Button(this);button.setText(label);button.setAllCaps(false);button.setMinHeight(dp(48));button.setOnClickListener(v->action.run());UiStyle.button(button);parent.addView(button,UiStyle.spaced(this));return button;}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
    @Override protected void onDestroy(){cancel();worker.shutdownNow();super.onDestroy();}
}
