package es.jesus.ampodcasts;

import static org.junit.Assert.*;
import android.content.Context;
import android.net.Uri;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.*;
import org.robolectric.annotation.Config;
import java.util.*;
import java.io.*;

@RunWith(RobolectricTestRunner.class) @Config(sdk=28)
public class RecommendationsTest {
    @Test public void favoriteWeightAndTopicDedupChooseInterestsFromActualHistory(){List<Recommendations.Heard> rows=Arrays.asList(new Recommendations.Heard("normal","A","https://example.com/a",Arrays.asList("Ciencia","Ciéncia","Publicidad")),new Recommendations.Heard("favorite","B","https://example.com/b",Arrays.asList("Historia")));List<Recommendations.Interest> interests=Recommendations.rank(rows,id->id.equals("favorite"));assertEquals(2,interests.size());assertEquals("Historia",interests.get(0).topic);assertEquals(3,interests.get(0).score);assertEquals(1,interests.get(1).score);}
    @Test public void catalogueSuggestionsAreRealDeduplicatedAndExcludeFollowedFeeds() throws Exception {Recommendations.Interest a=new Recommendations.Interest("Ciencia","A",1),b=new Recommendations.Interest("Historia","B",1);int[] calls={0};List<Recommendations.Suggestion> found=Recommendations.search(Arrays.asList(a,b),new HashSet<>(Arrays.asList("https://example.com/followed")),topic->{calls[0]++;return Arrays.asList(new Podcast("Followed","https://example.com/followed"),new Podcast("New","https://example.com/new"));});assertEquals(2,calls[0]);assertEquals(1,found.size());assertEquals("Ciencia",found.get(0).reason.topic);assertEquals("New",found.get(0).podcast.title);}
    @Test public void historyNeedsOptInAndIsBoundedToOneHundredEpisodes() throws Exception {Context c=RuntimeEnvironment.getApplication();GeminiTopics.Content themes=GeminiTopics.parse(GeminiTopicsTest.data(),120000,new ArrayList<>());Podcast p=new Podcast("Program","https://example.com/feed");Recommendations.record(c,new LibraryEntry(new Episode("off","Off","","https://example.com/off.mp3"),p),themes);assertTrue(Recommendations.history(c).isEmpty());Recommendations.enabled(c,true);for(int i=0;i<105;i++)Recommendations.record(c,new LibraryEntry(new Episode("id"+i,"Audio","","https://example.com/a.mp3"),p),themes);assertEquals(100,Recommendations.history(c).size());assertEquals("id104",Recommendations.history(c).get(0).id);Recommendations.clear(c);assertTrue(Recommendations.history(c).isEmpty());}
    @Test public void trackerCountsListeningRatherThanPositionAndClearResetsTheCurrentWindow() throws Exception {Context c=RuntimeEnvironment.getApplication();Repository r=new Repository(c);Podcast p=new Podcast("Program","https://example.com/feed");r.addPodcast(p);LibraryEntry e=new LibraryEntry(new Episode("listen","Audio","","https://example.com/a.mp3"),p);r.remember(e);java.io.File dir=GeminiPreparation.directory(c);dir.mkdirs();File file=new File(dir,UUID.randomUUID()+".audio");try(OutputStream out=new FileOutputStream(file)){out.write(new byte[100]);}GeminiTopics.Content themes=GeminiTopics.parse(GeminiTopicsTest.data(),120000,new ArrayList<>());AdSegments.save(c,e.episode.id,new AdSegments.Record(0,120000,e.episode.url,"gemini-test",new ArrayList<>(),new HashSet<>(),true,file.getName(),100,themes));Recommendations.enabled(c,true);Recommendations.Tracker tracker=new Recommendations.Tracker();Uri uri=Uri.fromFile(file);for(int i=0;i<30;i++)tracker.tick(c,r,e.episode.id,uri,true,i*1000);assertTrue(Recommendations.history(c).isEmpty());tracker.tick(c,r,e.episode.id,uri,true,30000);assertEquals(1,Recommendations.history(c).size());Recommendations.clear(c);tracker.tick(c,r,e.episode.id,uri,true,31000);assertTrue(Recommendations.history(c).isEmpty());tracker.tick(c,r,e.episode.id,uri,false,90000);assertTrue(Recommendations.history(c).isEmpty());Recommendations.enabled(c,false);for(int i=91;i<130;i++)tracker.tick(c,r,e.episode.id,uri,true,i*1000);assertTrue(Recommendations.history(c).isEmpty());}
}
